# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0
registries:
  fabric:
    type: maven-repository
    url: https://maven.fabricmc.net
updates:
  - assignees: [qwertycxz]
    commit-message:
      include: scope
      prefix: actions
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - assignees: [qwertycxz]
    commit-message:
      include: scope
      prefix: gradle
    directory: /
    package-ecosystem: gradle
    registries: '*'
    schedule:
      interval: daily
version: 2
