# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup GraalVM 24 with Gradle
        uses: ./.github/actions/setup
      - run: gradle check
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
permissions:
  contents: read
