# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@main
      with:
        cache: gradle
        distribution: orcale
        java-version: 24
on: workflow_call
